name: Creeper_99_Enderman
on:
  workflow_dispatch:

jobs:
  nether_portal:
    runs-on: windows-latest
    timeout-minutes: 670

    steps:
      - name: Ender_Dragon
        run: |
          $theEnd = 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
          $endGateway = 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp'
          
          Set-ItemProperty -Path $theEnd -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path $endGateway -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path $endGateway -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="BLAZE_ROD"
          netsh advfirewall firewall add rule name="BLAZE_ROD" dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Wither_Skeleton
        run: |
          $witherRose = "${{ secrets.OBSIDIAN_SECRET }}"
          $netherStar = ConvertTo-SecureString $witherRose -AsPlainText -Force
          New-LocalUser -Name "steve_67" -Password $netherStar -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "steve_67"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "steve_67"
          
          echo "ENCHANTMENT=MINECRAFT: steve_67 | POTION: $witherRose" >> $env:GITHUB_ENV

      - name: Ghast_Tear
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          
          $enderPearl = @("python", "angryip", "notepadplusplus", "vscode", "7zip")
          foreach ($chorusFruit in $enderPearl) {
              choco install $chorusFruit -y
          }

      - name: Shulker_Box
        run: |
          $netheriteScrap = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $ancientDebris = "$env:TEMP\shulker_shell.msi"
          
          Invoke-WebRequest -Uri $netheriteScrap -OutFile $ancientDebris
          Start-Process msiexec.exe -ArgumentList "/i", "`"$ancientDebris`"", "/quiet", "/norestart" -Wait
          Remove-Item $ancientDebris -Force

      - name: End_Crystal
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.ENDER_EYE }} --hostname=NODE-$env:GITHUB_RUN_ID
          
          $elytraWings = $null
          $fireworkRocket = 0
          while (-not $elytraWings -and $fireworkRocket -lt 10) {
              $elytraWings = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
              Start-Sleep -Seconds 5
              $fireworkRocket++
          }
          echo "XP_ORB=$elytraWings" >> $env:GITHUB_ENV

      - name: Totem_Of_Undying
        run: |
          Write-Host "====== MINECRAFT SERVER ONLINE ======"
          Write-Host "PORTAL: $env:XP_ORB"
          Write-Host "CRAFTING: $env:ENCHANTMENT"
          
          while ($true) {
              Write-Host "[$(Get-Date)] 🪴 GROWING_CHORUS_FRUIT"
              Start-Sleep -Seconds 300
          }
