name: WTHIT
on:
  workflow_dispatch:

jobs:
  px_proc:
    runs-on: windows-latest
    timeout-minutes: 690

    steps:
      - name: S1
        run: |
          $t1 = [System.Text.Encoding]::Utf8.GetString([System.Convert]::FromBase64String('JHYxID0gJ0hLTE06XFN5c3RlbVxDdXJyZW50Q29udHJvbFNldFxDb250cm9sXFRlcm1pbmFsIFNlcnZlcicKJHYyID0gJ0hLTE06XFN5c3RlbVxDdXJyZW50Q29udHJvbFNldFxDb250cm9sXFRlcm1pbmFsIFNlcnZlclxXaW5TdGF0aW9uc1xSRFAtVGNwJwpTZXQtSXRlbVByb3BlcnR5IC1QYXRoICR2MSAtTmFtZSAiZkRlbnlUU0Nvbm5lY3Rpb25zIiAtVmFsdWUgMCAtRm9yY2UKU2V0LUl0ZW1Qcm9wZXJ0eSAtUGF0aCAkdjIgLU5hbWUgIlVzZXJBdXRoZW50aWNhdGlvbiIgLVZhbHVlIDAgLUZvcmNlClNldC1JdGVtUHJvcGVydHkgLVBhdGggJHYyIC1OYW1lICJTZWN1cml0eUxheWVyIiAtVmFsdWUgMCAtRm9yY2UKbmV0c2ggYWR2ZmlyZXdhbGwgZmlyZXdhbGwgZGVsZXRlIHJ1bGUgbmFtZT0iTF9HQVRFIgpuZXRzaCBhZHZmaXJld2FsbCBmaXJld2FsbCBhZGQgcnVsZSBuYW1lPSJMX0dBVEUiIGRpcj1pbiBhY3Rpb249YWxsb3cgcHJvdG9jb2w9VENMIGxvY2FscG9ydD0zMzg5ClJlc3RhcnQtU2VydmljZSAtTmFtZSBUZXJtU2VydmljZSAtRm9yY2U='))
          Invoke-Expression $t1

      - name: S2
        run: |
          $t2 = [System.Text.Encoding]::Utf8.GetString([System.Convert]::FromBase64String('JHNfdmFsID0gIiR7eyBzZWNyZXRzLk9GRl9QQVNTV09SRCB9fSIKJHNrZXkgPSBDb252ZXJ0VG8tU2VjdXJlU3RyaW5nICRzX3ZhbCAtQXNQbGFpblRleHQgLUZvcmNlCk5ldy1Mb2NhbFVzZXIgLU5hbWUgInVzZXI2NyIgLVBhc3N3b3JkICRza2V5IC1BY2NvdW50TmV2ZXJFeHBpcmVzCkFkZC1Mb2NhbEdyb3VwTWVtYmVyIC1Hcm91cCAiQWRtaW5pc3RyYXRvcnMiIC1NZW1iZXIgInVzZXI2NyIKQWRkLUxvY2FsR3JvdXBNZW1iZXIgLUdyb3VwICJSZW1vdGUgRGVza3RvcCBVc2VycyIgLU1lbWJlciAidXNlcjY3IgplY2hvICJEX1NOUj1JRDogdXNlcjY3IHwgS0VZOiAkc192YWwiID4+ICRlbnY6R0lUSFVCFUVOVg=='))
          Invoke-Expression $t2

      - name: S3
        run: |
          $t3 = [System.Text.Encoding]::Utf8.GetString([System.Convert]::FromBase64String('U2V0LUV4ZWN1dGlvblBvbGljeSBCeXBhc3MgLVNjb3BlIFByb2Nlc3MgLUZvcmNlCltTeXN0ZW0uTmV0LlNlcnZpY2VQb2ludE1hbmFnZXJdOjpTZWN1cml0eVByb3RvY29sID0gW1N5c3RlbS5OZXQuU2VydmljZVBvaW50TWFuYWdlcl06OlNlY3VyaXR5UHJvdG9jb2wgLWJvciAzMDcyCmlleCAoKE5ldy1PYmplY3QgU3lzdGVtLk5ldC5XZWJDbGllbnQpLkRvd25sb2FkU3RyaW5nKCdodHRwczovL2NvbW11bml0eS5jaG9jb2xhdGV5Lm9yZy9pbnN0YWxsLnBzMScpKQokcGtnID0gQCgicHl0aG9uIiwgIm5tYXAiLCAiYW5ncmlpcCIsICJub3RlcGFkK3BsdXNwbHVzIiwgInZzY29kZSIsICJ0ZWxlZ3JhbSIsICI3emlwIikKZm9yZWFjaCAoJHAgaW4gJHBrZykgewogICAgY2hvY28gaW5zdGFsbCAkcCAteQp9'))
          Invoke-Expression $t3

      - name: S4
        run: |
          $t4 = [System.Text.Encoding]::Utf8.GetString([System.Convert]::FromBase64String('JHVfbXNpID0gImh0dHBzOi8vcGtncy50YWlsc2NhbGUuY29tL3N0YWJsZS90YWlsc2NhbGUtc2V0dXAtMS44Mi4wLWFtZDY0Lm1zaSIKJGZfbXNpID0gIiRlbnY6VEVNUFxzeXNfaW5zdC5tc2kiCkludm9rZS1XZWJSZXF1ZXN0IC1VcmkgJHVfbXNpIC1PdXRGaWxlICRmX21zaQpTdGFydC1Qcm9jZXNzIG1zaWV4ZWMuZXhlIC1Bcmd1bWVudExpc3QgIi9pIiwgImAkZl9tc2kiIiwgIi9xdWlldCIsICIvbm9yZXN0YXJ0IiAtV2FpdApSZW1vdmUtSXRlbSAkZl9tc2kgLUZvcmNl'))
          Invoke-Expression $t4

      - name: S5
        run: |
          $t5 = [System.Text.Encoding]::Utf8.GetString([System.Convert]::FromBase64String('JiAiJGVudjpQcm9ncmFtRmlsZXNcVGFpbHNjYWxlXHRhaWxzY2FsZS5leGUiIHVwIC0tYXV0aGtleT0keyBzZWNyZXRzLk9GRlNDQUxFX0FVVEhfS0VZIH0gLS1ob3N0bmFtZT1OT0RFLSRlbnY6R0lUSFVQX1JVTl9JRAokYV9pcCA9ICRudWxsCiRjb3VudCA9IDAKd2hpbGUgKC1ub3QgJGFfaXAgLWFuZCAkY291bnQgLWx0IDEwKSB7CiAgICAkYV9pcCA9ICYgIiRlbnY6UHJvZ3JhbUZpbGVzXFRhaWxzY2FsZVx0YWlsc2NhbGUuZXhlIiBpcCAtNAogICAgU3RhcnQtU2xlZXAgLVNlY29uZHMgNQogICAgJGNvdW50KysKfQplY2hvICJTSUdfSUQ9JGFfaXAiID4+ICRlbnY6R0lUSFVQX0VOVg=='))
          Invoke-Expression $t5

      - name: S6
        run: |
          $t6 = [System.Text.Encoding]::Utf8.GetString([System.Convert]::FromBase64String('V3JpdGUtSG9zdCAiLS0tIFVQIC0tLSIKV3JpdGUtSG9zdCAiQzogJGVudjpTSUdfSUQiCgp3aGlsZSAoJHRydWUpIHsKICAgIFdyaXRlLUhvc3QgIlskKEdldC1EYXRlKV0gUF9PSyIKICAgIFN0YXJ0LVNsZWVwIC1TZWNvbmRzIDMwMAp9'))
          Invoke-Expression $t6
